- hosts: sites
  user: ubuntu

  pre_tasks:
     - raw: sudo apt-get -y install python-minimal
     # action: setup will gather facts after python2 has been installed
     - action: setup
  
  tasks:
    - name: install nginx
      become: True
      apt: pkg=nginx state=present

    - name: Install common packages
      apt: pkg={{ item }} state=present
      become: True
      with_items:        
        - python-dev
        - python-pip

    - name: start nginx every bootup
      become: True
      service: name=nginx state=started enabled=yes
    
    - name: Install virtualenv
      become: True
      pip:
        name: virtualenv

    - name: Install production server requirements
      pip: name={{ item }} state=latest
      sudo: True
      with_items:
        - greenlet
        - gevent
        - gunicorn
        - supervisor

    - name: reload env
      become: True
      shell: source ~/.bashrc
      args:
        executable: /bin/bash
